#
# wpa_supplicant.conf
#

country=NZ

network={
	ssid="My SSID"
	psk="My password"
	proto=WPA2
	key_mgmt=WPA-PSK
}

network={
	ssid="My other SSID"
	psk="My other password"
	proto=WPA2
	key_mgmt=WPA-PSK
}


